"""Branded ReportLab PDF deliverables.

Four document types:
  1. Individual anonymous feedback PDF   (student-facing) — rating meters (peer vs
     self), performance + pay grade + grade adjustment, what teammates valued,
     where to focus next, and the quality of the feedback the student gave.
  2. Team self-reported contribution PDF  (team-facing)
  3. Instructor section summary PDF       (instructor-only, landscape, all data)
  4. Instructor confidential feedback PDF  (instructor-only)

Privacy rule enforced by build_individual_pdf: each student PDF contains ONLY
that student's name/team — no cross-student data leakage.
"""
from __future__ import annotations

import io
import math
from typing import List

from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas

from . import branding as B
from .grading import StudentResult, TeamResult

PAGE_W, PAGE_H = letter
MARGIN = 0.75 * inch


# --------------------------------------------------------------------------- #
# Low-level helpers
# --------------------------------------------------------------------------- #
def _header(c: canvas.Canvas, title: str, subtitle: str = "",
            page_w: float = PAGE_W, page_h: float = PAGE_H) -> float:
    c.setFillColor(B.NAVY)
    c.rect(0, page_h - 1.15 * inch, page_w, 1.15 * inch, fill=1, stroke=0)
    c.setFillColor(B.GREEN_LIGHT)
    c.rect(0, page_h - 1.20 * inch, page_w, 0.06 * inch, fill=1, stroke=0)
    c.setFillColor(B.WHITE)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(MARGIN, page_h - 0.62 * inch, B.BRAND)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(MARGIN, page_h - 0.82 * inch, B.TAGLINE)
    c.setFont("Helvetica-Bold", 13)
    c.drawRightString(page_w - MARGIN, page_h - 0.62 * inch, title)
    if subtitle:
        c.setFont("Helvetica", 9)
        c.drawRightString(page_w - MARGIN, page_h - 0.82 * inch, subtitle)
    return page_h - 1.5 * inch


def _footer(c: canvas.Canvas, note: str = "", page_w: float = PAGE_W) -> None:
    c.setFillColor(B.GREY)
    c.setFont("Helvetica", 7.5)
    c.drawString(MARGIN, 0.5 * inch, note or "Generated by PeerParley — confidential")
    c.drawRightString(page_w - MARGIN, 0.5 * inch, "peerparley")


def _wrap(c, text, x, y, width, font="Helvetica", size=10, leading=14, color=B.NAVY):
    c.setFont(font, size)
    c.setFillColor(color)
    for line in simpleSplit(text, font, size, width):
        if y < MARGIN + 0.5 * inch:
            c.showPage()
            y = PAGE_H - MARGIN
            c.setFont(font, size); c.setFillColor(color)
        c.drawString(x, y, line)
        y -= leading
    return y


def _is_nan(x) -> bool:
    try:
        return math.isnan(float(x))
    except (TypeError, ValueError):
        return True


def _page_guard(c, y, needed=1.0 * inch, note="Anonymous peer feedback — shared only with you."):
    """Break to a new page when `needed` vertical space isn't left.

    Added in v2 because an approved narrative can run several paragraphs, which
    made the individual PDF the first document here that reliably overflows one
    page. Without this a section heading could print two lines above the margin
    and its body start on the next page, orphaning the title. The footer is
    stamped on the outgoing page before the break, so a two-page feedback report
    carries its confidentiality note on both sheets rather than only the last.
    """
    if y - needed >= MARGIN + 0.5 * inch:
        return y
    _footer(c, note)
    c.showPage()
    return PAGE_H - MARGIN


def _section(c, y, title, color=B.NAVY, width=2.4 * inch):
    c.setFillColor(color); c.setFont("Helvetica-Bold", 11)
    c.drawString(MARGIN, y, title)
    y -= 8
    c.setStrokeColor(B.GREEN_LIGHT); c.setLineWidth(2)
    c.line(MARGIN, y, MARGIN + width, y)
    return y - 16


def _bullets(c, y, items, color, empty="None submitted this cycle."):
    items = [t for t in items if t and t.strip()]
    if not items:
        return _wrap(c, empty, MARGIN, y, PAGE_W - 2 * MARGIN,
                     "Helvetica-Oblique", 10, 14, B.GREY)
    for txt in items:
        c.setFillColor(color); c.setFont("Helvetica-Bold", 11)
        c.drawString(MARGIN, y + 1, "•")
        y = _wrap(c, txt, MARGIN + 14, y, PAGE_W - 2 * MARGIN - 14,
                  "Helvetica", 10, 14, B.NAVY)
        y -= 6
    return y


def _grade_meter(c, x, y, w, signed_pct):
    h = 0.28 * inch
    c.setFillColor(B.GREY_LIGHT)
    c.roundRect(x, y, w, h, 4, fill=1, stroke=0)
    mid = x + w / 2
    c.setStrokeColor(B.GREY); c.setLineWidth(1)
    c.line(mid, y - 2, mid, y + h + 2)
    frac = max(-1, min(1, signed_pct / 15.0))
    c.setFillColor(B.grade_color(signed_pct))
    if frac >= 0:
        c.roundRect(mid, y + 3, (w / 2) * frac, h - 6, 3, fill=1, stroke=0)
    else:
        bw = (w / 2) * abs(frac)
        c.roundRect(mid - bw, y + 3, bw, h - 6, 3, fill=1, stroke=0)
    c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(x + w / 2, y + h + 6,
                        f"{'+' if signed_pct >= 0 else ''}{signed_pct:g}% vs team score")


def _perf_pill(c, x, y, label):
    colors = {"High": B.GREEN, "Expected": B.GREY, "Adequate": B.GREY, "Low": B.AMBER}
    col = colors.get(label, B.GREY)
    w = 1.2 * inch
    c.setFillColor(col)
    c.roundRect(x, y, w, 0.26 * inch, 8, fill=1, stroke=0)
    c.setFillColor(B.WHITE); c.setFont("Helvetica-Bold", 9)
    c.drawCentredString(x + w / 2, y + 0.08 * inch, label.upper())


def _dim_meter(c, x, y, label, peer_val, peer_letter, self_val, self_letter, show_self):
    """One dimension row: label · filled bar (peer avg) · self tick · letter badges."""
    bar_x = x + 1.55 * inch
    bar_w = 2.35 * inch
    h = 0.16 * inch
    c.setFont("Helvetica", 9.5); c.setFillColor(B.NAVY)
    c.drawString(x, y + 1, label)
    c.setFillColor(B.GREY_LIGHT)
    c.roundRect(bar_x, y, bar_w, h, 3, fill=1, stroke=0)
    pv = 0.0 if _is_nan(peer_val) else max(0.0, min(1.0, peer_val))
    c.setFillColor(B.GREEN)
    c.roundRect(bar_x, y, bar_w * pv, h, 3, fill=1, stroke=0)
    if show_self and not _is_nan(self_val):
        sx = bar_x + bar_w * max(0.0, min(1.0, self_val))
        c.setStrokeColor(B.NAVY); c.setLineWidth(1.6)
        c.line(sx, y - 2, sx, y + h + 2)
    # letter badges
    c.setFont("Helvetica-Bold", 10); c.setFillColor(B.NAVY)
    c.drawString(bar_x + bar_w + 8, y, peer_letter or "—")
    if show_self:
        c.setFont("Helvetica", 9); c.setFillColor(B.GREY)
        c.drawString(bar_x + bar_w + 34, y, (self_letter or "—"))


# --------------------------------------------------------------------------- #
# 1. Individual anonymous feedback PDF (student-facing)
# --------------------------------------------------------------------------- #
_REPORT_ALL = {"performance": True, "grade_adjustment": True, "dimensions": True,
               "pay_grade": True, "valued": True, "focus": True,
               "response_quality": True, "narrative": True}


def build_individual_pdf(m: StudentResult, eval_no: str = "", course: str = "",
                         report: dict = None, narrative: str = "") -> bytes:
    """Student feedback PDF. `report` (dict of booleans) controls which sections
    appear; anything omitted defaults to shown.

    `narrative` is the instructor-approved AI summary of this student's peer
    comments, or "" for none. It is passed in rather than read from `m` on
    purpose: ``feedback_ai.approved_narratives`` is the only thing that produces
    these strings, so an unapproved draft cannot reach a PDF by some other
    route. The narrative appears *above* the raw comment bullets and never
    replaces them — a student is entitled to their teammates' actual words, and
    a summary they cannot check against the source is worth less, not more.
    """
    rep = {**_REPORT_ALL, **(report or {})}
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    sub = f"Evaluation {eval_no}" if eval_no else ""
    y = _header(c, "Peer Feedback", sub)

    c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 15)
    c.drawString(MARGIN, y, m.name)
    c.setFont("Helvetica", 10); c.setFillColor(B.GREY)
    c.drawString(MARGIN, y - 16, f"Team {m.team}" + (f"  ·  {course}" if course else ""))
    y -= 42

    # ---- rating meters (peer average vs self) ----
    dims = [("Team player", m.peer_vals[0], m.team_player, m.self_vals[0], m.self_team_player),
            ("Quantity of work", m.peer_vals[1], m.quantity, m.self_vals[1], m.self_quantity),
            ("Quality of work", m.peer_vals[2], m.quality, m.self_vals[2], m.self_quality),
            ("Effect on team", m.peer_vals[3], m.effect, m.self_vals[3], m.self_effect)]
    show_self = m.self_responded
    if rep["dimensions"] and any(lbl for _, _, lbl, _, _ in dims):
        y = _section(c, y, "How your teammates rated you", B.NAVY)
        c.setFont("Helvetica", 7.5); c.setFillColor(B.GREY)
        c.drawString(MARGIN + 1.55 * inch, y + 2, "peer average")
        c.drawString(MARGIN + 1.55 * inch + 2.5 * inch, y + 2,
                     "peer / self grade" if show_self else "grade")
        y -= 8
        for label, pv, pl, sv, sl in dims:
            _dim_meter(c, MARGIN, y, label, pv, pl, sv, sl, show_self)
            y -= 20
        if show_self:
            c.setFont("Helvetica-Oblique", 8); c.setFillColor(B.GREY)
            c.drawString(MARGIN, y, "Filled bar = teammates' average · tick = your self-rating.")
            y -= 12
        y -= 6

    # ---- performance · pay grade · grade adjustment ----
    pay_shown = rep["pay_grade"] and not _is_nan(m.pay_grade)
    row_used = False
    if rep["performance"]:
        _perf_pill(c, MARGIN, y - 4, m.performance); row_used = True
    if pay_shown:
        c.setFont("Helvetica", 10); c.setFillColor(B.NAVY)
        c.drawString(MARGIN + (1.4 * inch if rep["performance"] else 0), y + 2,
                     f"Pay grade: {m.pay_grade:.0%} of the team average*")
        row_used = True
    if row_used:
        y -= 30
    if rep["grade_adjustment"]:
        _grade_meter(c, MARGIN, y - 6, PAGE_W - 2 * MARGIN, m.signed_pct)
        y -= 54

    # ---- instructor-approved narrative summary of the written comments ----
    if rep.get("narrative", True) and (narrative or "").strip():
        y = _page_guard(c, y, needed=1.4 * inch)
        y = _section(c, y, "Summary of your peer feedback", B.NAVY, width=3.0 * inch)
        for para in [p.strip() for p in (narrative or "").split("\n") if p.strip()]:
            y = _wrap(c, para, MARGIN, y, PAGE_W - 2 * MARGIN,
                      "Helvetica", 10, 14.5, B.NAVY)
            y -= 8
        y = _wrap(c, "Written from your teammates' comments below and reviewed by "
                     "your instructor before release.",
                  MARGIN, y, PAGE_W - 2 * MARGIN, "Helvetica-Oblique", 8, 11, B.GREY)
        y -= 14

    # ---- what teammates valued (green) / where to focus (amber) ----
    if rep["valued"]:
        y = _page_guard(c, y, needed=1.0 * inch)
        y = _section(c, y, "What your teammates valued", B.GREEN)
        y = _bullets(c, y, m.contributions or m.public_comments, B.GREEN,
                     "No contribution highlights were submitted this cycle.")
        y -= 8
    if rep["focus"] and m.improvements:
        y = _page_guard(c, y, needed=1.0 * inch)
        y = _section(c, y, "Where to focus next", B.AMBER)
        y = _bullets(c, y, m.improvements, B.AMBER,
                     "No improvement suggestions were submitted this cycle.")
        y -= 8

    # ---- the feedback you gave (response quality) ----
    if rep["response_quality"] and (not _is_nan(m.response_Q) or m.response_points):
        y = _section(c, y, "The feedback you gave your teammates", B.NAVY)
        qtxt = "—" if _is_nan(m.response_Q) else f"{m.response_Q:.0%}"
        y = _wrap(c, f"Written-comment support (how well your comments back up your ratings): "
                     f"{qtxt}   ·   Points earned for your feedback: {m.response_points}",
                  MARGIN, y, PAGE_W - 2 * MARGIN, "Helvetica", 10, 14, B.NAVY)
        y -= 8

    if pay_shown:
        c.setFillColor(B.GREY); c.setFont("Helvetica-Oblique", 8)
        c.drawString(MARGIN, MARGIN + 0.15 * inch,
                     "* Pay grade shows your average received allocation vs the team average; "
                     "100% = an even share.")
    _footer(c, "Anonymous peer feedback — shared only with you.")
    c.showPage(); c.save()
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# 2. Team self-reported contribution PDF
# --------------------------------------------------------------------------- #
def build_team_contribution_pdf(team: TeamResult, eval_no: str = "") -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = _header(c, "Team Contributions", f"Team {team.team}")
    c.setFillColor(B.GREY); c.setFont("Helvetica", 9)
    c.drawString(MARGIN, y, "Self-reported allocation of 100 points across the team.")
    y -= 26
    c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 10)
    c.drawString(MARGIN, y, "Member")
    c.drawString(MARGIN + 3.0 * inch, y, "Avg received")
    c.drawString(MARGIN + 4.4 * inch, y, "Performance")
    y -= 6
    c.setStrokeColor(B.GREY_LIGHT); c.setLineWidth(1)
    c.line(MARGIN, y, PAGE_W - MARGIN, y); y -= 16
    for m in team.members:
        c.setFillColor(B.NAVY); c.setFont("Helvetica", 10)
        c.drawString(MARGIN, y, m.name)
        avg = (sum(m.received_breakdown) / len(m.received_breakdown)) if m.received_breakdown else 0
        c.drawString(MARGIN + 3.0 * inch, y, f"{avg:.1f} / {m.expected_share:g}")
        col = {"High": B.GREEN, "Expected": B.GREY, "Adequate": B.GREY,
               "Low": B.AMBER}.get(m.performance, B.GREY)
        c.setFillColor(col); c.setFont("Helvetica-Bold", 9)
        c.drawString(MARGIN + 4.4 * inch, y, m.performance)
        y -= 18
        if y < MARGIN + inch:
            _footer(c); c.showPage(); y = PAGE_H - MARGIN
    _footer(c, "Team contribution summary — shared with the whole team.")
    c.showPage(); c.save()
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# 3. Instructor section summary PDF  (landscape, all data)
# --------------------------------------------------------------------------- #
def build_section_summary_pdf(teams: List[TeamResult], course: str = "",
                              eval_no: str = "") -> bytes:
    buf = io.BytesIO()
    pw, ph = landscape(letter)
    c = canvas.Canvas(buf, pagesize=landscape(letter))
    y = _header(c, "Instructor Section Summary", course or "", pw, ph)
    c.setFillColor(B.GREY); c.setFont("Helvetica", 9)
    c.drawString(MARGIN, y, f"{len(teams)} teams  ·  "
                 f"{sum(len(t.members) for t in teams)} students"
                 + (f"  ·  Eval {eval_no}" if eval_no else ""))
    y -= 22

    # column layout (inches from left margin)
    cols = [("Name", 0.0), ("TmPl", 3.2), ("Qty", 3.7), ("Qual", 4.2), ("Effect", 4.7),
            ("Pay", 5.4), ("Ratio", 5.9), ("A", 6.5), ("Q", 6.9), ("Resp.Pts", 7.3),
            ("Mult", 8.1), ("Grade Δ", 8.7), ("Perf", 9.4)]

    def col_header():
        c.setFont("Helvetica-Bold", 8); c.setFillColor(B.GREY)
        for label, dx in cols:
            c.drawString(MARGIN + dx * inch, yy[0], label)
        yy[0] -= 12
        c.setStrokeColor(B.GREY_LIGHT); c.setLineWidth(0.8)
        c.line(MARGIN, yy[0] + 4, pw - MARGIN, yy[0] + 4)

    yy = [y]
    for t in teams:
        if yy[0] < MARGIN + 1.2 * inch:
            _footer(c, page_w=pw); c.showPage(); yy[0] = ph - MARGIN
        c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 11)
        c.drawString(MARGIN, yy[0], f"Team {t.team}")
        c.setFont("Helvetica", 8); c.setFillColor(B.GREY)
        c.drawRightString(pw - MARGIN, yy[0], f"Team score {t.team_score:g}")
        yy[0] -= 14
        col_header()
        for m in t.members:
            c.setFont("Helvetica", 8); c.setFillColor(B.NAVY)
            vals = [m.name[:30], m.team_player or "—", m.quantity or "—", m.quality or "—",
                    m.effect or "—", "" if _is_nan(m.pay_grade) else f"{m.pay_grade:.0%}",
                    f"{m.peer_ratio:g}", f"{m.A:g}", f"{m.Q:g}", str(m.response_points),
                    f"{m.multiplier:g}", "", m.performance[:9]]
            for (label, dx), v in zip(cols, vals):
                if label == "Grade Δ":
                    c.setFillColor(B.grade_color(m.signed_pct))
                    c.drawString(MARGIN + dx * inch, yy[0],
                                 f"{'+' if m.signed_pct >= 0 else ''}{m.signed_pct:g}%")
                    c.setFillColor(B.NAVY)
                else:
                    c.drawString(MARGIN + dx * inch, yy[0], v)
            yy[0] -= 12
            if yy[0] < MARGIN + 0.9 * inch:
                _footer(c, page_w=pw); c.showPage(); yy[0] = ph - MARGIN
        yy[0] -= 10

    if yy[0] < MARGIN + 1.6 * inch:
        _footer(c, page_w=pw); c.showPage(); yy[0] = ph - MARGIN
    c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 9)
    c.drawString(MARGIN, yy[0], "What each column means"); yy[0] -= 13
    legend = [
        "TmPl / Qty / Qual / Effect = letter grades from the 4-statement rating matrix.",
        "Pay = average received allocation vs the team average.  Ratio = received vs fair share.",
        "A = evaluator agreement weight.  Q = support behind the ratings received (drives the multiplier).",
        "Resp.Pts = points earned for the QUALITY of the feedback this student wrote.",
        "Mult = final grade multiplier.  Grade Δ = signed adjustment vs the team score.",
        "Perf = performance from the forced ranking (High / Adequate / Low).",
    ]
    for ln in legend:
        c.setFont("Helvetica", 8); c.setFillColor(B.GREY)
        c.drawString(MARGIN, yy[0], "• " + ln); yy[0] -= 11

    # ---- confidential comments to the instructor ----
    conf_rows = [(t.team, m.name, [x for x in m.confidential_comments if x.strip()])
                 for t in teams for m in t.members
                 if any(x.strip() for x in m.confidential_comments)]
    if conf_rows:
        _footer(c, page_w=pw); c.showPage(); yy[0] = ph - MARGIN
        c.setFillColor(B.RED); c.setFont("Helvetica-Bold", 12)
        c.drawString(MARGIN, yy[0], "Confidential comments to the instructor")
        yy[0] -= 6
        c.setFont("Helvetica", 8); c.setFillColor(B.GREY)
        c.drawString(MARGIN, yy[0], "Not released to students.")
        yy[0] -= 8
        c.setStrokeColor(B.GREEN_LIGHT); c.setLineWidth(1.5)
        c.line(MARGIN, yy[0], pw - MARGIN, yy[0]); yy[0] -= 18
        for team, name, notes in conf_rows:
            if yy[0] < MARGIN + 1.0 * inch:
                _footer(c, page_w=pw); c.showPage(); yy[0] = ph - MARGIN
            c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 9.5)
            c.drawString(MARGIN, yy[0], f"{name}  ·  Team {team}"); yy[0] -= 14
            for txt in notes:
                c.setFont("Helvetica", 9); c.setFillColor(B.NAVY)
                for line in simpleSplit("— " + txt, "Helvetica", 9, pw - 2 * MARGIN - 0.1 * inch):
                    if yy[0] < MARGIN + 0.7 * inch:
                        _footer(c, page_w=pw); c.showPage(); yy[0] = ph - MARGIN
                    c.drawString(MARGIN + 0.1 * inch, yy[0], line); yy[0] -= 12
                yy[0] -= 4
            yy[0] -= 6

    _footer(c, "Instructor section summary — confidential.", page_w=pw)
    c.showPage(); c.save()
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# 4. Instructor confidential feedback PDF
# --------------------------------------------------------------------------- #
def build_confidential_pdf(teams: List[TeamResult], course: str = "",
                           eval_no: str = "") -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = _header(c, "Confidential Feedback", course or "")
    c.setFillColor(B.RED); c.setFont("Helvetica-Bold", 9)
    c.drawString(MARGIN, y, "INSTRUCTOR ONLY — do not distribute to students.")
    y -= 24
    for t in teams:
        for m in t.members:
            conf = [x for x in m.confidential_comments if x.strip()]
            if not conf:
                continue
            if y < MARGIN + 1.2 * inch:
                _footer(c); c.showPage(); y = PAGE_H - MARGIN
            c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 10.5)
            c.drawString(MARGIN, y, f"{m.name}  ·  Team {t.team}")
            y -= 16
            for txt in conf:
                y = _wrap(c, "— " + txt, MARGIN + 0.1 * inch, y,
                          PAGE_W - 2 * MARGIN - 0.1 * inch, "Helvetica", 9.5, 13, B.NAVY)
                y -= 6
            y -= 8
    _footer(c, "Confidential instructor feedback.")
    c.showPage(); c.save()
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# 5. Evaluation comparison PDF  (across rounds, instructor-only)
# --------------------------------------------------------------------------- #
def build_comparison_pdf(course: str, evals) -> bytes:
    """evals = [(eval_no, [TeamResult, ...]), ...] — one entry per round.
    Landscape table: each student's individual score and grade Δ across rounds."""
    buf = io.BytesIO()
    pw, ph = landscape(letter)
    c = canvas.Canvas(buf, pagesize=landscape(letter))
    y = _header(c, "Evaluation Comparison", course or "", pw, ph)
    c.setFillColor(B.GREY); c.setFont("Helvetica", 9)
    c.drawString(MARGIN, y, "Individual score and grade adjustment (Δ) for each student "
                 f"across {len(evals)} evaluations.")
    y -= 22

    by_eval, team_of, names = {}, {}, set()
    for en, teams in evals:
        d = {}
        for t in teams:
            for m in t.members:
                d[m.name] = m
                team_of[m.name] = t.team
                names.add(m.name)
        by_eval[en] = d
    students = sorted(names, key=lambda nm: (str(team_of.get(nm, "")), nm.lower()))
    eval_nos = [en for en, _ in evals]

    name_w = 2.6 * inch
    col_w = (pw - 2 * MARGIN - name_w) / max(1, len(eval_nos))

    def head():
        c.setFont("Helvetica-Bold", 9); c.setFillColor(B.NAVY)
        c.drawString(MARGIN, yy[0], "Student  ·  Team")
        for i, en in enumerate(eval_nos):
            c.drawString(MARGIN + name_w + i * col_w, yy[0], f"Eval {en}  (score / Δ)")
        yy[0] -= 6
        c.setStrokeColor(B.GREY_LIGHT); c.setLineWidth(0.8)
        c.line(MARGIN, yy[0], pw - MARGIN, yy[0]); yy[0] -= 14

    yy = [y]
    head()
    for nm in students:
        if yy[0] < MARGIN + 0.8 * inch:
            _footer(c, page_w=pw); c.showPage(); yy[0] = ph - MARGIN; head()
        c.setFont("Helvetica", 9); c.setFillColor(B.NAVY)
        c.drawString(MARGIN, yy[0], f"{nm[:30]}  ·  Team {team_of.get(nm, '')}")
        for i, en in enumerate(eval_nos):
            m = by_eval[en].get(nm)
            x = MARGIN + name_w + i * col_w
            if m is None:
                c.setFillColor(B.GREY); c.setFont("Helvetica-Oblique", 9)
                c.drawString(x, yy[0], "—")
            else:
                c.setFillColor(B.NAVY); c.setFont("Helvetica", 9)
                c.drawString(x, yy[0], f"{m.individual_score:g}")
                c.setFillColor(B.grade_color(m.signed_pct)); c.setFont("Helvetica-Bold", 8)
                c.drawString(x + 0.7 * inch, yy[0],
                             f"{'+' if m.signed_pct >= 0 else ''}{m.signed_pct:g}%")
        yy[0] -= 13

    _footer(c, "Evaluation comparison — instructor only.", page_w=pw)
    c.showPage(); c.save()
    return buf.getvalue()
